### ISSUE TITLE
question

### ISSUE THREAD

**Issue by ds5j** [TimoMatzen/RBM#1]
Hi,
  This is a nice rbm example.  I wanted to use your fasion example but the data seems to be missing some records:
> str(Fashion)
List of 4
 $ trainX: num [1:784, 1:40000] 0 0 0 0 0 0 0 0 0 0 ...
 $ trainY: int [1:50000] 2 9 6 0 3 4 4 5 4 8 ...
 $ testX : num [1:784, 1:1000] 0 0 0 0.00392 0 ...
 $ testY : int [1:10000] 6 7 8 4 2 1 4 7 0 5 ...

Train X has 40k rows and train Y has 50K and in the test data it has 1k in X but Y is 10k.
Online it seems to indicate the train should be 60k and test 10k.
Do you have another copy of this that is not posted that corrects this?
thanks

**Comment by TimoMatzen** [comment]
Hi ds5j, this is a really late reply, but I have just fixed this problem! Sorry that it took such a long time and thanks for noticing!
